### ISSUE TITLE
Mussort creates filenames that are too long

### ISSUE THREAD

**Issue by johannspies** [zerodogg/mussort#4]
Example:

Rename: iTunes/Music/Music/Netherlands_Radio_Philharmonic_Orchestra/Mendelssohn_Symphony_#2/0_Mendelssoh_Symphon_#_I_Fla_Op_5_Hym_O_Praise-5_Sagt_E_Di_Ih_Erlos_Seid_E_Zahle_Unsr_Trane.mp3 -> Annegeer_Stumphius-Young-Hee_Kim_-_Matthias_Bleidorm_-_Edo_de_Waart_Netherlands_Radio_Philharmonic_Orchestra/Mendelssohn:_Symphony_2/05-Annegeer_Stumphius-Young-Hee_Kim_-_Matthias_Bleidorm_-_Edo_De_Waart_Netherlands_Radio_Philharmonic_Orchestra-Mendelssohn:_Symphony_2_In_B_Flat,_Op._52,_Hymn_Of_Praise-5._Sagte_Es,_Die_Ihr_Erlost_Seid._Er_Zahlet_Unsre_Tranen_Tenor,_Recitativo_and_Solo.mp3
Error: Unable to move /home/js/Music/iTunes/Music/Music/Netherlands_Radio_Philharmonic_Orchestra/Mendelssohn_Symphony_#2/0_Mendelssoh_Symphon_#_I_Fla_Op_5_Hym_O_Praise-5_Sagt_E_Di_Ih_Erlos_Seid_E_Zahle_Unsr_Trane.mp3 to /home/js/Music/Annegeer_Stumphius-Young-Hee_Kim_-_Matthias_Bleidorm_-_Edo_de_Waart_Netherlands_Radio_Philharmonic_Orchestra/Mendelssohn:_Symphony_2//05-Annegeer_Stumphius-Young-Hee_Kim_-_Matthias_Bleidorm_-_Edo_De_Waart_Netherlands_Radio_Philharmonic_Orchestra-Mendelssohn:_Symphony_2_In_B_Flat,_Op._52,_Hymn_Of_Praise-5._Sagte_Es,_Die_Ihr_Erlost_Seid._Er_Zahlet_Unsre_Tranen_Tenor,_Recitativo_and_Solo.mp3: File name too long

This is on Debian - mussort version 0.3-3

**Comment by zerodogg** [comment]
Fixed in 0.4
