### ISSUE TITLE
Please tag version 0.3.1 in git

### ISSUE THREAD

**Issue by satta** [zerodogg/mussort#6]
Could you please add a release tag for 0.3.1 if it's ready? The NEWS file suggests a new version is out but the latest tag here is 0.3.

Thanks!

**Comment by zerodogg** [comment]
Hi,
0.3.1 is not ready as there are some failing tests for it right now that I have yet to track down. It is fairly stable in use though.

- Eskild

**Comment by zerodogg** [comment]
Uh, so, I am obviously not really paying attention today. I was thinking of a separate project. Duh. I'll release it very soon, thanks for the notification.

Eskild

**Comment by satta** [comment]
Many thanks! I will wait for the new tag notification.

**Comment by satta** [comment]
Just wondering if you have had any time to look at the new release... thanks!

**Comment by zerodogg** [comment]
Version 0.4 is now tagged
