### ISSUE TITLE
add a README with basic information

### ISSUE THREAD

**Issue by fedelibre** [zerodogg/mussort#7]
@zerodogg can you please add a README.md file?
I would add:

1. A description. Taken from the website:
>mussort is a simple tool that sorts a music collection.
>It recursively searches a directory for MP3, OGG Vorbis and FLAC files, processing them one by one. It then reads the information from the file and puts them into a newly sorted directory tree. 

2. Installation instructions (sudo make install). I could find only `vorbis-tools` as dependency.

3. Usage instructions and limits (filesystem limits, #5 ; audio tag supported, etc.)

About the last point, is ID3 the only tag system supported? I see that mussort cannot recognize mp3 files tagged with some other metadata container. I can see the metadata in my file manager (Nautilus) for the following file:

    $ id3v2 -l f522738872.mp3 
    f522738872.mp3: No ID3 tag

**Comment by zerodogg** [comment]
I'll add a README.

Wrt. other tag systems. It only supports ID3 v1 or v2 for MP3 files, given that ID3 is the de-facto standard for MP3 tags. If you have a file with other tags, feel free to send it my way and I'll have a look if it is possible to implement support for it. I'd appreciate it if you'd open up a new issue for that though.
